### ISSUE TITLE
"Compressing" progress shows incomplete

### ISSUE THREAD

**Issue by kenlyon** [ffflorian/jszip-cli#37] opened 2018-11-26 21:53 UTC
When I run a script that calls jszip-cli, I find that the "Compressing" line never gets to 100%, although the task finishes. It typically shows somewhere  between 60-80%.

I think it just needs one last update after it gets to the end.

**Comment by ffflorian** [comment] 2018-11-26 22:04
Hi @kenlyon,
thanks for the report. I will investigate that.

**Comment by ffflorian** [comment] 2018-12-04 07:49
This is probably related to https://github.com/visionmedia/node-progress/issues/182.

**Comment by ffflorian** [comment] 2018-12-08 10:05
@kenlyon 

This should have been fixed with https://github.com/ffflorian/jszip-cli/pull/41. I just released [v2.1.3](https://www.npmjs.com/package/@ffflorian/jszip-cli/v/2.1.3). Can you check if the issue is resolved for you?

**Comment by kenlyon** [comment] 2018-12-09 05:55
Yes, that looks much better now. It now shows 100% at the end. Thanks so much for your quick response in addressing this problem!

**Comment by ffflorian** [comment] 2018-12-09 10:49
Great 🙂

**Closed by ffflorian** 2018-12-09 10:49 UTC
